# This automation activates the "Work Mode" at 9:00 AM on workdays.
# 
# id: Unique identifier for the automation.
# alias: Human-readable name for the automation.
# description: Brief explanation of what the automation does.
# trigger: Specifies the condition that triggers the automation.
#   - platform: The platform type, in this case, time.
#   - at: The specific time when the automation should trigger (9:00 AM).
# condition: Conditions that must be met for the automation to run.
#   - condition: The type of condition, in this case, state.
#   - entity_id: The entity to check the condition against (workday sensor).
#   - state: The required state of the entity (must be 'on' indicating a workday).
# action: The actions to perform when the automation is triggered and conditions are met.
#   - service: The service to call (input_boolean.turn_on).
#   - target: The target entity for the service (input_boolean.work_mode).

id: 'activate_work_mode'
alias: "Activate Work Mode"
description: "Activates the 'Work Mode' at 9:00 AM on work days."
trigger:
  - platform: time
    at: "09:00:00"
condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.work_mode

