id: '1729208446521'
alias: Main Bedroom Lamps Switch
description: ''
triggers:
- type: changed_states
  device_id: a2104672138b009a73d9bb16165060ab
  entity_id: bfda308d403c155f96a44ccc1a928887
  domain: switch
  trigger: device
conditions: []
actions:
- if:
  - condition: device
    type: is_on
    device_id: a2104672138b009a73d9bb16165060ab
    entity_id: bfda308d403c155f96a44ccc1a928887
    domain: switch
  then:
  - action: light.turn_on
    metadata: {}
    data: {}
    target:
      device_id:
      - 6c7e3bccf347718fa42e0fa2b2e8b610
      - ed65efdcde2b64954eb12e9c95eff529
  - action: homeassistant.turn_on
    metadata: {}
    data: {}
    target:
      device_id:
      - 6b99c2fa0e663e12b299f6824de9fcf9
      - 30aee2d47eaae89c45bae6abd3bac2cf
  else:
  - action: light.turn_off
    metadata: {}
    data: {}
    target:
      device_id:
      - 6c7e3bccf347718fa42e0fa2b2e8b610
      - ed65efdcde2b64954eb12e9c95eff529
  - action: homeassistant.turn_off
    metadata: {}
    data: {}
    target:
      device_id:
      - 6b99c2fa0e663e12b299f6824de9fcf9
      - 30aee2d47eaae89c45bae6abd3bac2cf
mode: single