# This automation enables the VSCode Tunnel switch when Home Assistant starts.
# 
# Description:
#   - Enables the VSCode Tunnel switch when Home Assistant starts.
#
# Mode:
#   - single: Ensures that the automation will not run multiple times concurrently.
#
# Triggers:
#   - Trigger: homeassistant
#     Event: start
#     Description: This trigger activates when Home Assistant starts.
#
# Conditions:
#   - None: This automation does not have any conditions.
#
# Actions:
#   - Action: switch.turn_on
#     Metadata: {}
#     Data: {}
#     Target:
#       Entity ID: switch.vscode_dev_tunnel_homeassistant
#     Description: This action turns on the VSCode Tunnel switch.

id: "enable_vscode_tunnel_on_startup"
alias: Enable VSCode Tunnel on Startup
description: "Enables the VSCode Tunnel switch when Home Assistant starts."
mode: single
triggers:
  - trigger: homeassistant
    event: start
conditions: []
actions:
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: switch.vscode_dev_tunnel_homeassistant
